<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DesaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data=[
['desa' => 'Sukodono',],
['desa' => 'Pagerkidul',],
['desa' => 'Gemaharjo',],
['desa' => 'Ploso',],
['desa' => 'Donorojo',],
['desa' => 'Punung',],
['desa' => 'Sidoharjo',],
['desa' => 'Dadapan',],
['desa' => 'Tanjungsari',],
['desa' => 'Arjowinangun',],
['desa' => 'Sukoharjo',],
['desa' => 'Tegalombo',],
['desa' => 'Bangunsari',],
['desa' => 'Sumberharjo',],
['desa' => 'Mentoro',],
['desa' => 'Gondosari',],
['desa' => 'Banjarsari',],
['desa' => 'Pacitan',],
['desa' => '',],
['desa' => 'Baleharjo',],
['desa' => 'Pagerejo',],
['desa' => 'Sooka',],
['desa' => 'Bungur',],
['desa' => 'Tulakan',],
['desa' => 'Purwoasri',],
['desa' => 'Pucangsewu',],
['desa' => 'Kendal',],
['desa' => 'Kayen',],
['desa' => 'Wiyoro',],
['desa' => 'Nanggungan',],
['desa' => 'Pringkuku',],
['desa' => 'Mujing',],
['desa' => 'Sukorejo',],
['desa' => 'Sumberejo',],
['desa' => 'Kluwih',],
['desa' => 'Temon',],
['desa' => 'Wareng',],
['desa' => 'Plumbungan',],
['desa' => 'Wonoasri',],
['desa' => 'Sidomulyo',],
['desa' => 'Sirnoboyo',],
['desa' => 'Tambakrejo',],
['desa' => 'Bogoharjo',],
['desa' => 'Karangnongko',],
['desa' => 'Ngadirojo',],
['desa' => 'Nawangan',],
['desa' => 'Banjarjo',],
['desa' => 'Widoro',],
['desa' => 'Tanjungpuro',],
['desa' => 'Gegeran',],
['desa' => 'Purworejo',],
['desa' => 'Pagerlor',],
['desa' => 'Gunungsari',],
['desa' => 'Watukarung',],
['desa' => 'Arjosari',],
['desa' => 'Kebonagung',],
['desa' => 'Wonokarto',],
['desa' => 'Wonosidi',],
['desa' => 'Losari',],
['desa' => 'Menadi',],
['desa' => 'Bubakan',],
['desa' => 'Nogosari',],
['desa' => 'Wonogondo',],
['desa' => 'Cokrokembang',],
['desa' => 'Ngile',],
['desa' => 'Kalak',],
['desa' => 'Karangrejo',],
['desa' => 'Ngadirejan',],
['desa' => 'Ketro',],
['desa' => 'Sedeng',],
['desa' => 'Kasihan',],
['desa' => 'Jetak',],
['desa' => 'Wonodadi Kulon',],
['desa' => 'Tremas',],
['desa' => 'Belah',],
['desa' => 'Gembong',],
['desa' => 'Worawari',],
['desa' => 'Nglaran',],
['desa' => 'Gendaran',],
['desa' => 'Pagutan',],
['desa' => 'Tanjunglor',],
['desa' => 'Kebondalem',],
['desa' => 'Kebonsari',],
['desa' => 'Ngromo',],
['desa' => 'Bolosingo',],
['desa' => 'Gedompol',],
['desa' => 'Klesem',],
['desa' => 'Kalipelus',],
['desa' => 'Gedangan',],
['desa' => 'Penggung',],
['desa' => 'Jatigunung',],
['desa' => 'Gunungrejo',],
['desa' => 'Sanggrahan',],
['desa' => 'Sedayu',],
['desa' => 'Candi',],
['desa' => 'Bandar',],
['desa' => 'Glinggangan',],
['desa' => 'Bomo',],
['desa' => 'Kembang',],
['desa' => 'Sambong',],
['desa' => 'Wonodadi Wetan',],
['desa' => 'Dersono',],
['desa' => 'Tokawi',],
['desa' => 'Pelem',],
['desa' => 'Ngunut',],
['desa' => 'Jlubang',],
['desa' => 'Tahunan',],
['desa' => 'Hadiwarno',],
['desa' => 'Tamanasri',],
['desa' => 'Jeruk',],
['desa' => 'Mlati',],
['desa' => 'Sudimoro',],
['desa' => 'Gasang',],
['desa' => 'Sembowo',],
['desa' => 'Kalikuning',],
['desa' => 'Tinatar',],
['desa' => 'Sekar',],
['desa' => 'Jatimalang',],
['desa' => 'Mendolo Lor',],
['desa' => 'Katipugal',],
['desa' => 'Sendang',],
['desa' => 'Gembuk',],
['desa' => 'Karanganyar',],
['desa' => 'Petungsinarang',],
['desa' => 'Piton',],
['desa' => 'Wonoanti',],
['desa' => 'Karanggede',],
['desa' => 'Ngreco',],
['desa' => 'Mantren',],
['desa' => 'Ketanggung',],
['desa' => 'Kemuning',],
['desa' => 'Hadiluwih',],
['desa' => 'Tahunan Baru',],
['desa' => 'Klepu',],
['desa' => 'Gawang',],
['desa' => 'Poko',],
['desa' => 'Kedungbendo',],
['desa' => 'Jetis Lor',],
['desa' => 'Ketepung',],
['desa' => 'Sempu',],
['desa' => 'Semanten',],
['desa' => 'Kledung',],
['desa' => 'Karangmulyo',],
['desa' => 'Padi',],
['desa' => 'Gondang',],
['desa' => 'Pakis Baru',],
['desa' => 'Wonosobo',],
['desa' => 'Mendolo Kidul',],
['desa' => 'Watupatok',],
['desa' => 'Borang',],
['desa' => 'Mangunharjo',],
['desa' => 'Gayuhan',],
['desa' => 'Ponggok',],
['desa' => 'Cangkring',],
['desa' => 'Punjung',],
['desa' => 'Tumpuk',],
['desa' => 'Pucangombo',],
['desa' => 'Bodag',],
['desa' => 'Ngumbul',],
['desa' => 'Cemeng',],
['desa' => 'Sugihwaras',],
['desa' => 'Jetiskidul',],
['desa' => 'Sobo',],
['desa' => 'Sawahan',],
        ];
        
        DB::table('desas')->insert($data);

    }
}
