<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KBLISeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['kode_kbli' => '86105', 'nama' => 'Aktivitas Klinik Swasta',],
            ['kode_kbli' => '03216', 'nama' => 'Pembesaran Crustacea Laut',],
            ['kode_kbli' => '47763', 'nama' => 'Perdagangan Eceran Pupuk Dan Pemberantas Hama',],
            ['kode_kbli' => '47112', 'nama' => 'Perdagangan Eceran Berbagai Macam Barang Yang Utamanya Makanan, Minuman Atau Tembakau Bukan Di Minimarket/Supermarket/Hypermarket (Tradisional)',],
            ['kode_kbli' => '10794', 'nama' => 'Industri Kerupuk, Keripik, Peyek Dan Sejenisnya',],
            ['kode_kbli' => '47249', 'nama' => 'Perdagangan Eceran Makanan Lainnya',],
            ['kode_kbli' => '47215', 'nama' => 'Perdagangan Eceran Hasil Perikanan',],
            ['kode_kbli' => '93229', 'nama' => 'Daya Tarik Wisata Alam Lainnya',],
            ['kode_kbli' => '41016', 'nama' => 'Konstruksi Gedung Pendidikan',],
            ['kode_kbli' => '42101', 'nama' => 'Konstruksi Bangunan Sipil Jalan',],
            ['kode_kbli' => '42201', 'nama' => 'Konstruksi Jaringan Irigasi dan Drainase',],
            ['kode_kbli' => '42202', 'nama' => 'Konstruksi Bangunan Sipil Pengolahan Air Bersih',],
            ['kode_kbli' => '41019', 'nama' => 'Konstruksi Gedung Lainnya',],
            ['kode_kbli' => '47611', 'nama' => 'Perdagangan Eceran Alat Tulis Menulis Dan Gambar',],
            ['kode_kbli' => '56102', 'nama' => 'Rumah/Warung Makan',],
            ['kode_kbli' => '47411', 'nama' => 'Perdagangan Eceran Komputer Dan Perlengkapannya',],
            ['kode_kbli' => '82110', 'nama' => 'Aktivitas Penyedia Gabungan Jasa Administrasi Kantor',],
            ['kode_kbli' => '47420', 'nama' => 'Perdagangan Eceran Khusus Peralatan Audio dan Video di Toko',],
            ['kode_kbli' => '47592', 'nama' => 'Perdagangan Eceran Peralatan Listrik Rumah Tangga Dan Peralatan Penerangan Dan Perlengkapannya',],
            ['kode_kbli' => '10710', 'nama' => 'Industri Produk Roti Dan Kue',],
            ['kode_kbli' => '90029', 'nama' => 'Aktivitas Pekerja Seni dan Pekerja Kreatif Lainnya ',],
            ['kode_kbli' => '47111', 'nama' => 'Perdagangan Eceran Berbagai Macam Barang Yang Utamanya Makanan, Minuman Atau Tembakau Di Minimarket/Supermarket/Hypermarket',],
            ['kode_kbli' => '47528', 'nama' => 'Perdagangan Eceran Berbagai Macam Material Bangunan',],
            ['kode_kbli' => '47511', 'nama' => 'Perdagangan Eceran Tekstil',],
            ['kode_kbli' => '47524', 'nama' => 'Perdagangan Eceran Semen, Kapur, Pasir Dan Batu',],
            ['kode_kbli' => '47521', 'nama' => 'Perdagangan Eceran Barang Logam Untuk Bahan Konstruksi',],
            ['kode_kbli' => '47529', 'nama' => 'Perdagangan Eceran Bahan Dan Barang Konstruksi Lainnya',],
            ['kode_kbli' => '45302', 'nama' => 'Perdagangan Eceran Suku Cadang Dan Aksesori Mobil',],
            ['kode_kbli' => '10216', 'nama' => 'Industri Berbasis Daging Lumatan Dan Surimi',],
            ['kode_kbli' => '55120', 'nama' => 'Hotel Melati',],
            ['kode_kbli' => '82190', 'nama' => 'Aktivitas Fotokopi, Penyiapan Dokumen dan Aktivitas Khusus Penunjang Kantor Lainnya',],
            ['kode_kbli' => '47714', 'nama' => 'Perdagangan Eceran Tas, Dompet, Koper, Ransel Dan Sejenisnya',],
            ['kode_kbli' => '47712', 'nama' => 'Perdagangan Eceran Sepatu, Sandal Dan Alas Kaki Lainnya',],
            ['kode_kbli' => '47711', 'nama' => 'Perdagangan Eceran Pakaian',],
            ['kode_kbli' => '56101', 'nama' => 'Restoran',],
            ['kode_kbli' => '46511', 'nama' => 'Perdagangan Besar Komputer dan Perlengkapan Komputer',],
            ['kode_kbli' => '64141', 'nama' => 'Koperasi Simpan Pinjam Primer (KSP Primer)',],
            ['kode_kbli' => '86101', 'nama' => 'Aktivitas Rumah Sakit Pemerintah',],
            ['kode_kbli' => '12011', 'nama' => 'Industri Sigaret Kretek Tangan',],
            ['kode_kbli' => '12091', 'nama' => 'Industri Pengeringan Dan Pengolahan Tembakau',],
            ['kode_kbli' => '01612', 'nama' => 'Jasa Pemupukan, Penanaman Bibit/Benih Dan Pengendalian Hama dan Gulma',],
            ['kode_kbli' => '46652', 'nama' => 'Perdagangan Besar Pupuk Dan Produk Agrokimia',],
            ['kode_kbli' => '52101', 'nama' => 'Pergudangan dan Penyimpanan',],
            ['kode_kbli' => '32909', 'nama' => 'Industri Pengolahan Lainnya YTDL',],
            ['kode_kbli' => '16101', 'nama' => 'Industri Penggergajian Kayu',],
            ['kode_kbli' => '01619', 'nama' => 'Jasa Penunjang Pertanian Lainnya',],
            ['kode_kbli' => '41011', 'nama' => 'Konstruksi Gedung Hunian',],
            ['kode_kbli' => '85495', 'nama' => 'Pendidikan Bimbingan Belajar Dan Konseling Swasta',],
            ['kode_kbli' => '47301', 'nama' => 'Perdagangan Eceran Bahan Bakar Minyak, Bahan Bakar Gas (BBG), dan Liquefied Petroleum Gas (LPG) di Sarana Pengisian Bahan Bakar Transportasi Darat, Laut, dan Udara',],
            ['kode_kbli' => '47725', 'nama' => 'Perdagangan Eceran Alat Laboratorium, Alat Farmasi Dan Alat Kesehatan Untuk Manusia',],
            ['kode_kbli' => '47599', 'nama' => 'Perdagangan Eceran Peralatan Dan Perlengkapan Rumah Tangga Lainnya YTDL',],
            ['kode_kbli' => '47723', 'nama' => 'Perdagangan Eceran Obat Tradisional Untuk Manusia',],
            ['kode_kbli' => '42102', 'nama' => 'Konstruksi Bangunan Sipil Jembatan, Jalan Layang, Fly Over, dan Underpass',],
            ['kode_kbli' => '47597', 'nama' => 'Perdagangan Eceran Alat Musik',],
            ['kode_kbli' => '47783', 'nama' => 'Perdagangan Eceran Barang Kerajinan Dari Logam',],
            ['kode_kbli' => '47796', 'nama' => 'Perdagangan Eceran Alat-alat Pertanian',],
            ['kode_kbli' => '47630', 'nama' => 'Perdagangan Eceran Khusus Peralatan Olahraga di Toko',],
            ['kode_kbli' => '47591', 'nama' => 'Perdagangan Eceran Furnitur',],
            ['kode_kbli' => '49431', 'nama' => 'Angkutan Bermotor untuk Barang Umum',],
            ['kode_kbli' => '47791', 'nama' => 'Perdagangan Eceran Mesin Pertanian Dan Perlengkapannya',],
            ['kode_kbli' => '47762', 'nama' => 'Perdagangan Eceran Tanaman Dan Bibit Tanaman ',],
            ['kode_kbli' => '47754', 'nama' => 'Perdagangan Eceran Pakan Ternak/Unggas/Ikan dan Hewan Piaraan',],
            ['kode_kbli' => '47726', 'nama' => 'Perdagangan Eceran Barang Dan Obat Farmasi Untuk Hewan Di Apotik Dan Bukan Di Apotik',],
            ['kode_kbli' => '41015', 'nama' => 'Konstruksi Gedung Kesehatan',],
            ['kode_kbli' => '41014', 'nama' => 'Konstruksi Gedung Perbelanjaan',],
            ['kode_kbli' => '41017', 'nama' => 'Konstruksi Gedung Penginapan',],
            ['kode_kbli' => '47413', 'nama' => 'Perdagangan Eceran Piranti Lunak (Software)',],
            ['kode_kbli' => '47214', 'nama' => 'Perdagangan Eceran Hasil Peternakan',],
            ['kode_kbli' => '47216', 'nama' => 'Perdagangan Eceran Hasil Kehutanan dan Perburuan',],
            ['kode_kbli' => '47781', 'nama' => 'Perdagangan Eceran Barang Kerajinan Dari Kayu, Bambu, Rotan, Pandan, Rumput Dan Sejenisnya',],
            ['kode_kbli' => '47997', 'nama' => 'Perdagangan Eceran Keliling Kertas, Barang Dari Kertas, Alat Tulis, Barang Cetakan, Alat Olahraga, Alat Musik, Alat Fotografi Dan Komputer',],
            ['kode_kbli' => '47192', 'nama' => 'Perdagangan Eceran Berbagai Macam Barang Yang Utamanya Bukan Makanan, Minuman Atau Tembakau (barang-barang Kelontong) Bukan Di Toserba (Department Store)',],
            ['kode_kbli' => '33119', 'nama' => 'Reparasi Produk Logam Pabrikasi Lainnya',],
            ['kode_kbli' => '47867', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Alat Kebersihan',],
            ['kode_kbli' => '42911', 'nama' => 'Konstruksi Bangunan Prasarana Sumber Daya Air',],
            ['kode_kbli' => '36001', 'nama' => 'Penampungan, Penjernihan dan Penyaluran Air Minum',],
            ['kode_kbli' => '47721', 'nama' => 'Perdagangan Eceran Barang Dan Obat Farmasi Untuk Manusia Di Apotik',],
            ['kode_kbli' => '74909', 'nama' => 'Aktivitas Profesional, Ilmiah dan Teknis Lainnya YTDL',],
            ['kode_kbli' => '45403', 'nama' => 'Perdagangan Eceran Sepeda Motor Baru',],
            ['kode_kbli' => '47302', 'nama' => 'Perdagangan Eceran Bahan Bakar Minyak, Bahan Bakar Gas (BBG), dan Liquefied Petroleum Gas (LPG) Selain Di Sarana Pengisian Bahan Bakar Transportasi Darat, Laut, dan Udara',],
            ['kode_kbli' => '47737', 'nama' => 'Perdagangan Eceran Pembungkus Dari Plastik',],
            ['kode_kbli' => '42918', 'nama' => 'Konstruksi Bangunan Sipil Fasilitas Olah Raga',],
            ['kode_kbli' => '41012', 'nama' => 'Konstruksi Gedung Perkantoran',],
            ['kode_kbli' => '42203', 'nama' => 'Konstruksi Bangunan Sipil Prasarana dan Sarana Sistem Pengolahan Limbah Padat, Cair, dan Gas',],
            ['kode_kbli' => '33121', 'nama' => 'Reparasi Mesin Untuk Keperluan Umum',],
            ['kode_kbli' => '47412', 'nama' => 'Perdagangan Eceran Peralatan Video Game Dan Sejenisnya',],
            ['kode_kbli' => '14120', 'nama' => 'Penjahitan Dan Pembuatan Pakaian Sesuai Pesanan',],
            ['kode_kbli' => '27409', 'nama' => 'Industri Peralatan Penerangan Lainnya',],
            ['kode_kbli' => '41018', 'nama' => 'Konstruksi Gedung Tempat Hiburan dan Olahraga',],
            ['kode_kbli' => '47772', 'nama' => 'Perdagangan Eceran Gas Elpiji',],
            ['kode_kbli' => '47722', 'nama' => 'Perdagangan Eceran Barang Dan Obat Farmasi Untuk Manusia Bukan Di Apotik',],
            ['kode_kbli' => '47414', 'nama' => 'Perdagangan Eceran Alat Telekomunikasi',],
            ['kode_kbli' => '47415', 'nama' => 'Perdagangan Eceran Mesin Kantor',],
            ['kode_kbli' => '47650', 'nama' => 'Perdagangan Eceran Kertas, Kertas Karton Dan Barang Dari Kertas/Karton',],
            ['kode_kbli' => '47731', 'nama' => 'Perdagangan Eceran Alat Fotografi Dan Perlengkapannya',],
            ['kode_kbli' => '95110', 'nama' => 'Reparasi Komputer dan Peralatan Sejenisnya',],
            ['kode_kbli' => '95120', 'nama' => 'Reparasi Peralatan Komunikasi',],
            ['kode_kbli' => '35129', 'nama' => 'Aktivitas penunjang tenaga listrik lainnya',],
            ['kode_kbli' => '47640', 'nama' => 'Perdagangan Eceran Khusus Alat Permainan dan Mainan Anak-anak di Toko',],
            ['kode_kbli' => '47793', 'nama' => 'Perdagangan Eceran Mesin Lainnya Dan Perlengkapannya',],
            ['kode_kbli' => '23990', 'nama' => 'Industri Barang Galian Bukan Logam Lainnya Ytdl',],
            ['kode_kbli' => '13999', 'nama' => 'Industri Tekstil Lainnya YTDL',],
            ['kode_kbli' => '01629', 'nama' => 'Jasa Penunjang Peternakan Lainnya',],
            ['kode_kbli' => '10631', 'nama' => 'Industri Penggilingan Padi Dan Penyosohan Beras',],
            ['kode_kbli' => '49429', 'nama' => 'Angkutan Darat Lainnya untuk Penumpang',],
            ['kode_kbli' => '16211', 'nama' => 'Industri Kayu Lapis',],
            ['kode_kbli' => '41013', 'nama' => 'Konstruksi Gedung Industri',],
            ['kode_kbli' => '42919', 'nama' => 'Konstruksi Bangunan Sipil Lainnya Ytdl',],
            ['kode_kbli' => '47523', 'nama' => 'Perdagangan Eceran Genteng, Batu Bata, Ubin Dan Sejenisnya Dari Tanah Liat, Kapur, Semen Atau Kaca',],
            ['kode_kbli' => '47526', 'nama' => 'Perdagangan Eceran Bahan Konstruksi Dari Kayu',],
            ['kode_kbli' => '01499', 'nama' => 'Pembibitan Dan Budidaya Aneka Ternak Lainnya',],
            ['kode_kbli' => '47752', 'nama' => 'Perdagangan Eceran Hewan Ternak',],
            ['kode_kbli' => '42207', 'nama' => 'Pembuatan/Pengeboran Sumur Air Tanah',],
            ['kode_kbli' => '43305', 'nama' => 'Dekorasi Eksterior',],
            ['kode_kbli' => '43120', 'nama' => 'Penyiapan Lahan',],
            ['kode_kbli' => '47733', 'nama' => 'Perdagangan Eceran Kaca Mata',],
            ['kode_kbli' => '03141', 'nama' => 'Jasa Sarana Produksi Penangkapan Ikan Di Perairan Darat',],
            ['kode_kbli' => '30111', 'nama' => 'Industri Kapal Dan Perahu',],
            ['kode_kbli' => '30112', 'nama' => 'Industri Bangunan Lepas Pantai Dan Bangunan Terapung',],
            ['kode_kbli' => '52109', 'nama' => 'Pergudangan dan Penyimpanan Lainnya',],
            ['kode_kbli' => '35201', 'nama' => 'Pengadaan Gas Alam Dan Buatan',],
            ['kode_kbli' => '35202', 'nama' => 'Distribusi Gas Alam Dan Buatan',],
            ['kode_kbli' => '74902', 'nama' => 'Aktivitas Konsultasi Bisnis Dan Broker Bisnis',],
            ['kode_kbli' => '46691', 'nama' => 'Perdagangan Besar Alat Laboratorium, Alat Farmasi Dan Alat Kedokteran Untuk Manusia',],
            ['kode_kbli' => '46610', 'nama' => 'Perdagangan Besar Bahan Bakar Padat, Cair Dan Gas Dan Produk YBDI',],
            ['kode_kbli' => '45401', 'nama' => 'Perdagangan Besar Sepeda Motor Baru',],
            ['kode_kbli' => '86103', 'nama' => 'Aktivitas Rumah Sakit Swasta',],
            ['kode_kbli' => '14111', 'nama' => 'Industri Pakaian Jadi (Konveksi) Dari Tekstil',],
            ['kode_kbli' => '49422', 'nama' => 'Angkutan Sewa',],
            ['kode_kbli' => '47219', 'nama' => 'Perdagangan Eceran Hasil Pertanian Lainnya',],
            ['kode_kbli' => '49412', 'nama' => 'Angkutan Antarkota Dalam Provinsi (AKDP) Bukan Bus, Dalam Trayek',],
            ['kode_kbli' => '49221', 'nama' => 'Angkutan Bus Pariwisata',],
            ['kode_kbli' => '03226', 'nama' => 'Pembenihan Ikan Air Tawar',],
            ['kode_kbli' => '03241', 'nama' => 'Jasa Sarana Produksi Budidaya Ikan Air Tawar',],
            ['kode_kbli' => '56210', 'nama' => 'Jasa Boga Untuk Suatu Event Tertentu (Event Catering)',],
            ['kode_kbli' => '78200', 'nama' => 'Aktivitas Penyediaan Tenaga Kerja Waktu Tertentu',],
            ['kode_kbli' => '47241', 'nama' => 'Perdagangan Eceran Beras',],
            ['kode_kbli' => '03231', 'nama' => 'Jasa Sarana Produksi Budidaya Ikan Laut',],
            ['kode_kbli' => '43904', 'nama' => 'Pemasangan Kerangka Baja',],
            ['kode_kbli' => '47211', 'nama' => 'Perdagangan Eceran Padi Dan Palawija',],
            ['kode_kbli' => '47729', 'nama' => 'Perdagangan Eceran Khusus Barang Dan Obat Farmasi, Alat Kedokteran, Parfum Dan Kosmetik Lainnya',],
            ['kode_kbli' => '47996', 'nama' => 'Perdagangan Eceran Keliling Bahan Bakar Dan Minyak Pelumas',],
            ['kode_kbli' => '90090', 'nama' => 'Aktivitas Hiburan, Seni dan Kreativitas Lainnya ',],
            ['kode_kbli' => '90012', 'nama' => 'Aktivitas Penunjang Seni Pertunjukan ',],
            ['kode_kbli' => '23957', 'nama' => 'Industri Mortar atau Beton Siap Pakai',],
            ['kode_kbli' => '43909', 'nama' => 'Konstruksi Khusus Lainnya Ytdl',],
            ['kode_kbli' => '08109', 'nama' => 'Penggalian batu, pasir dan tanah liat lainnya',],
            ['kode_kbli' => '43303', 'nama' => 'Pengecatan',],
            ['kode_kbli' => '43224', 'nama' => 'Instalasi Pendingin Dan Ventilasi Udara',],
            ['kode_kbli' => '43301', 'nama' => 'Pengerjaan Pemasangan Kaca Dan Alumunium',],
            ['kode_kbli' => '18111', 'nama' => 'Industri Pencetakan Umum',],
            ['kode_kbli' => '37022', 'nama' => 'Treatment dan Pembuangan Air Limbah Berbahaya',],
            ['kode_kbli' => '16295', 'nama' => 'Industri Kayu Bakar dan Pelet Kayu',],
            ['kode_kbli' => '47612', 'nama' => 'Perdagangan Eceran Hasil Pencetakan Dan Penerbitan',],
            ['kode_kbli' => '63122', 'nama' => 'Portal Web Dan/Atau Platform Digital Dengan Tujuan Komersial',],
            ['kode_kbli' => '49211', 'nama' => 'Angkutan bus Antarkota Antarprovinsi (AKAP)',],
            ['kode_kbli' => '63121', 'nama' => 'Portal Web Dan/Atau Platform Digital Tanpa Tujuan Komersial',],
            ['kode_kbli' => '46430', 'nama' => 'Perdagangan Besar Alat Fotografi dan Barang Optik',],
            ['kode_kbli' => '46638', 'nama' => 'Perdagangan Besar Berbagai Macam Material Bangunan',],
            ['kode_kbli' => '55130', 'nama' => 'Pondok Wisata',],
            ['kode_kbli' => '86903', 'nama' => 'Aktivitas Pelayanan Penunjang Kesehatan',],
            ['kode_kbli' => '68200', 'nama' => 'Real Estat  Atas Dasar Balas Jasa (Fee) Atau Kontrak',],
            ['kode_kbli' => '47724', 'nama' => 'Perdagangan Eceran Kosmetik Untuk Manusia',],
            ['kode_kbli' => '01199', 'nama' => 'Pertanian tanaman semusim lainnya ytdl',],
            ['kode_kbli' => '08919', 'nama' => 'Pertambangan Mineral, Bahan Kimia Dan Bahan Pupuk Lainnya',],
            ['kode_kbli' => '46522', 'nama' => 'Perdagangan Besar Disket, Flash Drive, Pita Audio dan Video, CD dan DVD Kosong',],
            ['kode_kbli' => '46632', 'nama' => 'Perdagangan Besar Kaca',],
            ['kode_kbli' => '81210', 'nama' => 'Aktivitas Kebersihan Umum Bangunan',],
            ['kode_kbli' => '47527', 'nama' => 'Perdagangan Eceran Cat, Pernis Dan Lak',],
            ['kode_kbli' => '47920', 'nama' => 'Perdagangan Eceran Atas Dasar Balas Jasa (Fee) Atau Kontrak',],
            ['kode_kbli' => '45407', 'nama' => 'Reparasi Dan Perawatan Sepeda Motor',],
            ['kode_kbli' => '45406', 'nama' => 'Perdagangan Eceran Suku Cadang Sepeda Motor Dan Aksesorinya',],
            ['kode_kbli' => '46900', 'nama' => 'Perdagangan Besar Berbagai Macam Barang',],
            ['kode_kbli' => '10217', 'nama' => 'Industri Pendinginan/Pengesan Ikan',],
            ['kode_kbli' => '46207', 'nama' => 'Perdagangan Besar Hasil Kehutanan Dan Perburuan',],
            ['kode_kbli' => '58130', 'nama' => 'Penerbitan Surat Kabar, Jurnal Dan Buletin Atau Majalah',],
            ['kode_kbli' => '46203', 'nama' => 'Perdagangan Besar Bunga Dan Tanaman Hias',],
            ['kode_kbli' => '46411', 'nama' => 'Perdagangan Besar Tekstil',],
            ['kode_kbli' => '46412', 'nama' => 'Perdagangan Besar Pakaian',],
            ['kode_kbli' => '46413', 'nama' => 'Perdagangan Besar Alas Kaki',],
            ['kode_kbli' => '46499', 'nama' => 'Perdagangan Besar Berbagai Barang Dan Perlengkapan Rumah Tangga Lainnya Ytdl',],
            ['kode_kbli' => '18120', 'nama' => 'Kegiatan Jasa Penunjang Pencetakan',],
            ['kode_kbli' => '46421', 'nama' => 'Perdagangan Besar Alat Tulis Dan Gambar',],
            ['kode_kbli' => '79121', 'nama' => 'Aktivitas Biro Perjalanan Wisata',],
            ['kode_kbli' => '45201', 'nama' => 'Reparasi Mobil',],
            ['kode_kbli' => '64145', 'nama' => 'Koperasi Simpan Pinjam dan Pembiayaan Syariah Primer (KSPPS Primer)',],
            ['kode_kbli' => '46209', 'nama' => 'Perdagangan Besar Hasil Pertanian Dan Hewan Hidup Lainnya',],
            ['kode_kbli' => '60202', 'nama' => 'Aktivitas Penyiaran dan Pemrograman Televisi Oleh Swasta',],
            ['kode_kbli' => '47735', 'nama' => 'Perdagangan Eceran Barang Perhiasan',],
            ['kode_kbli' => '46414', 'nama' => 'Perdagangan Besar Barang Lainnya Dari Tekstil',],
            ['kode_kbli' => '46512', 'nama' => 'Perdagangan Besar Piranti Lunak',],
            ['kode_kbli' => '46521', 'nama' => 'Perdagangan Besar Suku Cadang Elektronik',],
            ['kode_kbli' => '46634', 'nama' => 'Perdagangan Besar Semen, Kapur, Pasir Dan Batu',],
            ['kode_kbli' => '46523', 'nama' => 'Perdagangan Besar Peralatan Telekomunikasi',],
            ['kode_kbli' => '71102', 'nama' => 'Aktivitas Keinsinyuran dan Konsultasi Teknis YBDI',],
            ['kode_kbli' => '49425', 'nama' => 'Angkutan Darat Wisata',],
            ['kode_kbli' => '52299', 'nama' => 'Aktivitas Penunjang Angkutan Lainnya YTDL',],
            ['kode_kbli' => '43211', 'nama' => 'Instalasi Listrik',],
            ['kode_kbli' => '36003', 'nama' => 'Aktivitas Penunjang Treatment Air',],
            ['kode_kbli' => '46422', 'nama' => 'Perdagangan Besar Barang Percetakan Dan Penerbitan Dalam Berbagai Bentuk',],
            ['kode_kbli' => '46339', 'nama' => 'Perdagangan Besar Makanan Dan Minuman Lainnya',],
            ['kode_kbli' => '77394', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak opsi Mesin Kantor Dan Peralatannya',],
            ['kode_kbli' => '18202', 'nama' => 'Reproduksi Media Rekaman Film Dan Video',],
            ['kode_kbli' => '59112', 'nama' => 'Aktivitas Produksi Film, Video dan Program Televisi Oleh Swasta',],
            ['kode_kbli' => '46696', 'nama' => 'Perdagangan Besar Barang Bekas Dan Sisa-sisa Tak Terpakai (Scrap)',],
            ['kode_kbli' => '73100', 'nama' => 'Periklanan',],
            ['kode_kbli' => '82302', 'nama' => 'Jasa Penyelenggara Event Khusus (Special Event)',],
            ['kode_kbli' => '74201', 'nama' => 'Aktivitas Fotografi',],
            ['kode_kbli' => '46695', 'nama' => 'Perdagangan Besar Barang Dari Kertas Dan Karton',],
            ['kode_kbli' => '79990', 'nama' => 'Jasa Reservasi Lainnya YBDI YTDL',],
            ['kode_kbli' => '03111', 'nama' => 'Penangkapan Pisces/Ikan Bersirip Di Laut',],
            ['kode_kbli' => '46491', 'nama' => 'Perdagangan Besar Peralatan Dan Perlengkapan Rumah Tangga',],
            ['kode_kbli' => '78421', 'nama' => 'Pelatihan Kerja Teknik Swasta',],
            ['kode_kbli' => '85321', 'nama' => 'Pendidikan Tinggi Akademik Swasta',],
            ['kode_kbli' => '85322', 'nama' => 'Pendidikan Tinggi Vokasi dan Profesi Swasta ',],
            ['kode_kbli' => '02119', 'nama' => 'Pemanfaatan kayu hutan tanaman lainnya',],
            ['kode_kbli' => '02111', 'nama' => 'Pemanfaatan Kayu Hutan Tanaman pada Hutan Produksi',],
            ['kode_kbli' => '08101', 'nama' => 'Penggalian Batu Hias Dan Batu Bangunan',],
            ['kode_kbli' => '08105', 'nama' => 'Penggalian Tanah dan Tanah Liat',],
            ['kode_kbli' => '08992', 'nama' => 'Penggalian Feldspar dan Kalsit',],
            ['kode_kbli' => '61921', 'nama' => 'Internet Service Provider',],
            ['kode_kbli' => '16214', 'nama' => 'Industri Veneer',],
            ['kode_kbli' => '47242', 'nama' => 'Perdagangan Eceran Roti, Kue Kering, serta Kue Basah dan Sejenisnya',],
            ['kode_kbli' => '47833', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Sepatu, Sandal Dan Alas Kaki Lainnya',],
            ['kode_kbli' => '46699', 'nama' => 'Perdagangan Besar Produk Lainnya YTDL',],
            ['kode_kbli' => '56109', 'nama' => 'Restoran dan penyediaan makanan keliling lainnya',],
            ['kode_kbli' => '47753', 'nama' => 'Perdagangan Eceran Ikan Hias',],
            ['kode_kbli' => '03229', 'nama' => 'Budidaya Ikan Air Tawar di Media Lainnya',],
            ['kode_kbli' => '47761', 'nama' => 'Perdagangan Eceran Bunga Potong/Florist',],
            ['kode_kbli' => '46494', 'nama' => 'Perdagangan Besar Perhiasan Dan Jam',],
            ['kode_kbli' => '02307', 'nama' => 'Pemungutan Madu',],
            ['kode_kbli' => '10793', 'nama' => 'Industri Makanan Dari Kedele Dan Kacang-kacangan Lainnya Bukan Kecap, Tempe Dan Tahu',],
            ['kode_kbli' => '16293', 'nama' => 'Industri Kerajinan Ukiran Dari Kayu Bukan Mebeller',],
            ['kode_kbli' => '95299', 'nama' => 'Reparasi Barang Rumah Tangga Dan Pribadi Lainnya',],
            ['kode_kbli' => '01411', 'nama' => 'Pembibitan Dan Budidaya Sapi Potong',],
            ['kode_kbli' => '66153', 'nama' => 'Pedagang Fisik Komoditi',],
            ['kode_kbli' => '31001', 'nama' => 'Industri Furnitur Dari Kayu',],
            ['kode_kbli' => '25920', 'nama' => 'Jasa Industri Untuk Berbagai Pengerjaan Khusus Logam Dan Barang Dari Logam',],
            ['kode_kbli' => '01442', 'nama' => 'Pembibitan Dan Budidaya Kambing Potong',],
            ['kode_kbli' => '01464', 'nama' => 'Budidaya Ayam Lokal dan Persilangannya',],
            ['kode_kbli' => '03112', 'nama' => 'Penangkapan Crustacea Di Laut',],
            ['kode_kbli' => '56103', 'nama' => 'Kedai Makanan',],
            ['kode_kbli' => '01469', 'nama' => 'Pembibitan Dan Budidaya Ternak Unggas Lainnya',],
            ['kode_kbli' => '47819', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Komoditi Tanaman Hias Dan Hasil Pertanian Lainnya',],
            ['kode_kbli' => '01136', 'nama' => 'Pertanian Jamur',],
            ['kode_kbli' => '01285', 'nama' => 'Pertanian Tanaman Obat atau Biofarmaka Rimpang',],
            ['kode_kbli' => '47912', 'nama' => 'Perdagangan Eceran Melalui Media Untuk Komoditi Tekstil, Pakaian, Alas Kaki Dan Barang Keperluan Pribadi',],
            ['kode_kbli' => '25999', 'nama' => 'Industri Barang Logam Lainnya YTDL',],
            ['kode_kbli' => '28224', 'nama' => 'Industri Mesin dan Perkakas Mesin Untuk Pengelasan Yang Menggunakan Arus Listrik',],
            ['kode_kbli' => '56104', 'nama' => 'Penyediaan Makanan Keliling/Tempat Tidak Tetap',],
            ['kode_kbli' => '01461', 'nama' => 'Budidaya Ayam Ras Pedaging',],
            ['kode_kbli' => '13134', 'nama' => 'Industri Batik',],
            ['kode_kbli' => '25112', 'nama' => 'Industri Barang Dari Logam Aluminium Siap Pasang Untuk Bangunan',],
            ['kode_kbli' => '47593', 'nama' => 'Perdagangan Eceran Barang Pecah Belah Dan Perlengkapan Dapur Dari Plastik',],
            ['kode_kbli' => '47797', 'nama' => 'Perdagangan Eceran Alat-alat Pertukangan',],
            ['kode_kbli' => '47862', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Alat Dan Perlengkapan Listrik',],
            ['kode_kbli' => '03115', 'nama' => 'Penangkapan/Pengambilan Induk/Benih Ikan Di Laut',],
            ['kode_kbli' => '16291', 'nama' => 'Industri Barang Anyaman Dari Rotan Dan Bambu',],
            ['kode_kbli' => '02121', 'nama' => 'Pemanfaatan Kayu Hutan Alam',],
            ['kode_kbli' => '33122', 'nama' => 'Reparasi Mesin Untuk Keperluan Khusus',],
            ['kode_kbli' => '49229', 'nama' => 'Angkutan Bus Tidak Dalam Trayek Lainnya',],
            ['kode_kbli' => '79111', 'nama' => 'Aktivitas Agen Perjalanan Wisata',],
            ['kode_kbli' => '77100', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Mobil, Bus, Truk Dan Sejenisnya',],
            ['kode_kbli' => '56303', 'nama' => 'Rumah Minum/Kafe',],
            ['kode_kbli' => '10771', 'nama' => 'Industri Kecap',],
            ['kode_kbli' => '08103', 'nama' => 'Penggalian Kerikil/Sirtu',],
            ['kode_kbli' => '46100', 'nama' => 'Perdagangan Besar Atas Dasar Balas Jasa (Fee) Atau Kontrak',],
            ['kode_kbli' => '01462', 'nama' => 'Budidaya Ayam Ras Petelur',],
            ['kode_kbli' => '45202', 'nama' => 'Pencucian Dan Salon Mobil',],
            ['kode_kbli' => '45301', 'nama' => 'Perdagangan Besar Suku Cadang Dan Aksesori Mobil',],
            ['kode_kbli' => '43213', 'nama' => 'Instalasi Elektronika',],
            ['kode_kbli' => '95210', 'nama' => 'Reparasi Alat-alat Elektronik Konsumen',],
            ['kode_kbli' => '47825', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Daging Olahan Dan Ikan Olahan',],
            ['kode_kbli' => '43304', 'nama' => 'Dekorasi Interior',],
            ['kode_kbli' => '46334', 'nama' => 'Perdagangan Besar Minuman Non Alkohol Bukan Susu',],
            ['kode_kbli' => '01135', 'nama' => 'Pertanian Aneka Umbi Palawija',],
            ['kode_kbli' => '02201', 'nama' => 'Pemanenan kayu',],
            ['kode_kbli' => '03259', 'nama' => 'Budidaya Biota Air Payau Lainnya',],
            ['kode_kbli' => '23921', 'nama' => 'Industri Batu Bata Dari Tanah Liat/Keramik',],
            ['kode_kbli' => '43309', 'nama' => 'Penyelesaian Konstruksi Bangunan Lainnya',],
            ['kode_kbli' => '03254', 'nama' => 'Pembesaran Crustacea Air Payau',],
            ['kode_kbli' => '47895', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Pakaian, Alas Kaki, Perlengkapan Pakaian Dan Barang Perlengkapan Pribadi Bekas',],
            ['kode_kbli' => '02113', 'nama' => 'Pemanfaatan kayu hutan tanaman rakyat',],
            ['kode_kbli' => '10799', 'nama' => 'Industri Produk Makanan Lainnya',],
            ['kode_kbli' => '46591', 'nama' => 'Perdagangan Besar Mesin Kantor dan Industri Pengolahan, Suku Cadang Dan Perlengkapannya',],
            ['kode_kbli' => '43221', 'nama' => 'Instalasi Saluran Air (Plambing)',],
            ['kode_kbli' => '47303', 'nama' => 'Perdagangan Eceran Minyak Pelumas Di Toko',],
            ['kode_kbli' => '43291', 'nama' => 'Instalasi Mekanikal',],
            ['kode_kbli' => '08106', 'nama' => 'Penggalian Gips',],
            ['kode_kbli' => '03221', 'nama' => 'Pembesaran Ikan Air Tawar Di Kolam',],
            ['kode_kbli' => '10219', 'nama' => 'Industri Pengolahan Dan Pengawetan Lainnya untuk Ikan',],
            ['kode_kbli' => '47826', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Minuman',],
            ['kode_kbli' => '46636', 'nama' => 'Perdagangan Besar Bahan Konstruksi Dari Kayu',],
            ['kode_kbli' => '16213', 'nama' => 'Industri Panel Kayu Lainnya',],
            ['kode_kbli' => '03242', 'nama' => 'Jasa Produksi Budidaya Ikan Air Tawar',],
            ['kode_kbli' => '45404', 'nama' => 'Perdagangan Eceran Sepeda Motor Bekas',],
            ['kode_kbli' => '46204', 'nama' => 'Perdagangan Besar Tembakau Rajangan',],
            ['kode_kbli' => '47882', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Mainan Anak-anak',],
            ['kode_kbli' => '55900', 'nama' => 'Penyediaan Akomodasi Lainnya',],
            ['kode_kbli' => '85492', 'nama' => 'Jasa Pendidikan Komputer (Teknologi Informasi dan Komunikasi) Swasta',],
            ['kode_kbli' => '62019', 'nama' => 'Aktivitas Pemrograman Komputer Lainnya',],
            ['kode_kbli' => '62029', 'nama' => 'Aktivitas Konsultasi Komputer dan Manajemen Fasilitas Komputer Lainnya',],
            ['kode_kbli' => '47212', 'nama' => 'Perdagangan Eceran Buah-buahan',],
            ['kode_kbli' => '96112', 'nama' => 'Aktivitas Salon Kecantikan',],
            ['kode_kbli' => '01220', 'nama' => 'Pertanian Buah-Buahan Tropis dan Subtropis',],
            ['kode_kbli' => '16221', 'nama' => 'Industri Barang Bangunan Dari Kayu',],
            ['kode_kbli' => '52215', 'nama' => 'Aktivitas Perparkiran di Luar Badan Jalan (Off Street Parking)',],
            ['kode_kbli' => '10750', 'nama' => 'Industri Makanan dan Masakan Olahan',],
            ['kode_kbli' => '47919', 'nama' => 'Perdagangan Eceran Melalui Media Untuk Berbagai Macam Barang Lainnya',],
            ['kode_kbli' => '49213', 'nama' => 'Angkutan bus Antarkota Dalam Provinsi (AKDP)',],
            ['kode_kbli' => '79922', 'nama' => 'Jasa interpreter wisata',],
            ['kode_kbli' => '47914', 'nama' => 'Perdagangan Eceran Melalui Media Untuk Barang Campuran Sebagaimana Tersebut Dalam 47911 S.D. 47913',],
            ['kode_kbli' => '47899', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Barang Lainnya',],
            ['kode_kbli' => '47596', 'nama' => 'Perdagangan Eceran Barang Pecah Belah Dan Perlengkapan Dapur Bukan Dari Plastik, Batu, Tanah Liat, Kayu, Bambu Atau Rotan',],
            ['kode_kbli' => '47222', 'nama' => 'Perdagangan Eceran Minuman Tidak Beralkohol',],
            ['kode_kbli' => '47230', 'nama' => 'Perdagangan Eceran Khusus Rokok dan Tembakau di Toko',],
            ['kode_kbli' => '47243', 'nama' => 'Perdagangan Eceran Kopi, Gula Pasir dan Gula Merah',],
            ['kode_kbli' => '45402', 'nama' => 'Perdagangan Besar Sepeda Motor Bekas',],
            ['kode_kbli' => '47991', 'nama' => 'Perdagangan Eceran Keliling Komoditi Makanan Dari Hasil Pertanian',],
            ['kode_kbli' => '02202', 'nama' => 'Usaha Pemungutan Kayu',],
            ['kode_kbli' => '01111', 'nama' => 'Pertanian Jagung',],
            ['kode_kbli' => '10391', 'nama' => 'Industri Tempe Kedelai',],
            ['kode_kbli' => '42206', 'nama' => 'Konstruksi Sentral Telekomunikasi',],
            ['kode_kbli' => '74113', 'nama' => 'Aktivitas Desain Tekstil, Fashion dan Apparel',],
            ['kode_kbli' => '47913', 'nama' => 'Perdagangan Eceran Melalui Media Untuk Barang Perlengkapan Rumah Tangga Dan Perlengkapan Dapur',],
            ['kode_kbli' => '25111', 'nama' => 'Industri Barang Dari Logam Bukan Aluminium Siap Pasang Untuk Bangunan',],
            ['kode_kbli' => '47739', 'nama' => 'Perdagangan eceran khusus barang baru lainnya ytdl',],
            ['kode_kbli' => '96990', 'nama' => 'Aktivitas Jasa Perorangan Lainnya YTDL',],
            ['kode_kbli' => '96111', 'nama' => 'Aktivitas Pangkas Rambut',],
            ['kode_kbli' => '61100', 'nama' => 'Aktivitas Telekomunikasi Dengan Kabel',],
            ['kode_kbli' => '61924', 'nama' => 'Jasa Interkoneksi Internet (NAP)',],
            ['kode_kbli' => '61994', 'nama' => 'Jasa Jual Kembali Jasa Telekomunikasi',],
            ['kode_kbli' => '62090', 'nama' => 'Aktivitas Teknologi Informasi Dan Jasa Komputer Lainnya',],
            ['kode_kbli' => '10761', 'nama' => 'Industri Pengolahan Kopi',],
            ['kode_kbli' => '01493', 'nama' => 'Pembibitan Dan Budidaya Lebah',],
            ['kode_kbli' => '61913', 'nama' => 'Jasa Internet Teleponi Untuk Keperluan Publik (ITKP)',],
            ['kode_kbli' => '55191', 'nama' => 'Penginapan Remaja (Youth Hostel)',],
            ['kode_kbli' => '35302', 'nama' => 'Produksi Es',],
            ['kode_kbli' => '10213', 'nama' => 'Industri Pembekuan Ikan',],
            ['kode_kbli' => '56304', 'nama' => 'Kedai Minuman',],
            ['kode_kbli' => '11051', 'nama' => 'Industri Air Kemasan',],
            ['kode_kbli' => '32120', 'nama' => 'Industri Perhiasan Imitasi dan Barang Sejenis',],
            ['kode_kbli' => '23963', 'nama' => 'Industri Barang Dari Batu Untuk Keperluan Rumah Tangga, Pajangan, dan Bahan Bangunan',],
            ['kode_kbli' => '47789', 'nama' => 'Perdagangan Eceran Barang Kerajinan Dan Lukisan Lainnya',],
            ['kode_kbli' => '32903', 'nama' => 'Industri Kerajinan YTDL',],
            ['kode_kbli' => '11090', 'nama' => 'Industri Minuman Lainnya',],
            ['kode_kbli' => '01193', 'nama' => 'Pertanian Tanaman Bunga',],
            ['kode_kbli' => '10762', 'nama' => 'Industri Pengolahan Herbal (herb infusion)',],
            ['kode_kbli' => '10772', 'nama' => 'Industri Bumbu Masak Dan Penyedap Masakan',],
            ['kode_kbli' => '96122', 'nama' => 'Aktivitas SPA (Sante Par Aqua)',],
            ['kode_kbli' => '81100', 'nama' => 'Aktivitas Penyedia Gabungan Jasa Penunjang Fasilitas',],
            ['kode_kbli' => '49432', 'nama' => 'Angkutan Bermotor untuk Barang Khusus',],
            ['kode_kbli' => '56305', 'nama' => 'Rumah/Kedai Obat Tradisional',],
            ['kode_kbli' => '01441', 'nama' => 'Pembibitan Dan Budidaya Domba Potong',],
            ['kode_kbli' => '19291', 'nama' => 'Industri Produk Dari Hasil Kilang Minyak Bumi',],
            ['kode_kbli' => '46335', 'nama' => 'Perdagangan Besar Rokok Dan Tembakau',],
            ['kode_kbli' => '21022', 'nama' => 'Industri Produk Obat Tradisional untuk Manusia',],
            ['kode_kbli' => '47191', 'nama' => 'Perdagangan Eceran Berbagai Macam Barang Yang Utamanya Bukan Makanan, Minuman Atau Tembakau Di Toserba (Department Store)',],
            ['kode_kbli' => '47213', 'nama' => 'Perdagangan Eceran Sayuran',],
            ['kode_kbli' => '23911', 'nama' => 'Industri Bata, Mortar, Semen, dan Sejenisnya yang Tahan Api',],
            ['kode_kbli' => '46592', 'nama' => 'Perdagangan Besar Alat Transportasi Laut, Suku Cadang Dan Perlengkapannya',],
            ['kode_kbli' => '74130', 'nama' => 'Aktivitas Desain Komunikasi Visual/ Desain Grafis',],
            ['kode_kbli' => '46631', 'nama' => 'Perdagangan Besar Barang Logam Untuk Bahan Konstruksi',],
            ['kode_kbli' => '11040', 'nama' => 'Industri Minuman Ringan',],
            ['kode_kbli' => '93239', 'nama' => 'Daya Tarik Wisata Buatan/Binaan Manusia Lainnya',],
            ['kode_kbli' => '46313', 'nama' => 'Perdagangan Besar Sayuran',],
            ['kode_kbli' => '42913', 'nama' => 'Konstruksi Bangunan Pelabuhan Perikanan',],
            ['kode_kbli' => '10614', 'nama' => 'Industri Tepung Campuran dan Adonan Tepung',],
            ['kode_kbli' => '46201', 'nama' => 'Perdagangan Besar Padi Dan Palawija',],
            ['kode_kbli' => '46202', 'nama' => 'Perdagangan Besar Buah Yang Mengandung Minyak',],
            ['kode_kbli' => '46312', 'nama' => 'Perdagangan Besar Buah-buahan',],
            ['kode_kbli' => '46314', 'nama' => 'Perdagangan Besar Kopi, Teh Dan Kakao',],
            ['kode_kbli' => '46319', 'nama' => 'Perdagangan Besar Bahan Makanan Dan Minuman Hasil Pertanian Lainnya',],
            ['kode_kbli' => '01443', 'nama' => 'Pembibitan Dan Budidaya Kambing Perah',],
            ['kode_kbli' => '47815', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Komoditi Hasil Perikanan',],
            ['kode_kbli' => '42204', 'nama' => 'Konstruksi Bangunan Sipil Elektrikal',],
            ['kode_kbli' => '47594', 'nama' => 'Perdagangan Eceran Barang Pecah Belah Dan Perlengkapan Dapur Dari Batu Atau Tanah Liat',],
            ['kode_kbli' => '71101', 'nama' => 'Aktivitas Arsitektur ',],
            ['kode_kbli' => '10722', 'nama' => 'Industri Gula Merah',],
            ['kode_kbli' => '47751', 'nama' => 'Perdagangan Eceran Hewan Piaraan (Pet Animals)',],
            ['kode_kbli' => '47828', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Pakan Ternak, Pakan Unggas Dan Pakan Ikan',],
            ['kode_kbli' => '96200', 'nama' => 'Aktivitas penatu',],
            ['kode_kbli' => '23932', 'nama' => 'Industri Perlengkapan Rumah Tangga Dari Tanah Liat/Keramik',],
            ['kode_kbli' => '23939', 'nama' => 'Industri Barang Tanah Liat/Keramik dan Porselen Lainnya Bukan Bahan Bangunan',],
            ['kode_kbli' => '47784', 'nama' => 'Perdagangan Eceran Barang Kerajinan Dari Keramik',],
            ['kode_kbli' => '02209', 'nama' => 'Usaha Kehutanan Lainnya',],
            ['kode_kbli' => '47595', 'nama' => 'Perdagangan Eceran Barang Pecah Belah Dan Perlengkapan Dapur Dari Kayu, Bambu Atau Rotan',],
            ['kode_kbli' => '23922', 'nama' => 'Industri Genteng Dari Tanah Liat/Keramik',],
            ['kode_kbli' => '01466', 'nama' => 'Pembibitan Dan Budidaya Burung Puyuh',],
            ['kode_kbli' => '28222', 'nama' => 'Industri Mesin dan Perkakas Mesin Untuk Pengerjaan Kayu',],
            ['kode_kbli' => '79119', 'nama' => 'Aktivitas Agen Perjalanan Lainnya',],
            ['kode_kbli' => '02112', 'nama' => 'Pemanfaatan kayu hutan tanaman hasil rehabilitasi pada hutan produksi',],
            ['kode_kbli' => '56290', 'nama' => 'Penyediaan Jasa Boga Periode Tertentu',],
            ['kode_kbli' => '68111', 'nama' => 'Real Estat Yang Dimiliki Sendiri Atau Disewa',],
            ['kode_kbli' => '01468', 'nama' => 'Pembibitan Ayam Ras',],
            ['kode_kbli' => '03225', 'nama' => 'Budidaya Ikan Hias Air Tawar',],
            ['kode_kbli' => '70209', 'nama' => 'Aktivitas Konsultasi Manajemen Lainnya',],
            ['kode_kbli' => '70204', 'nama' => 'Aktivitas Konsultansi Manajemen Industri',],
            ['kode_kbli' => '01463', 'nama' => 'Pembibitan Ayam Lokal dan Persilangannya',],
            ['kode_kbli' => '52219', 'nama' => 'Aktivitas Penunjang Angkutan Darat Lainnya',],
            ['kode_kbli' => '01131', 'nama' => 'Pertanian Hortikultura Sayuran Daun',],
            ['kode_kbli' => '01134', 'nama' => 'Pertanian Hortikultura Sayuran Umbi',],
            ['kode_kbli' => '31009', 'nama' => 'Industri Furnitur Lainnya',],
            ['kode_kbli' => '96121', 'nama' => 'Rumah Pijat',],
            ['kode_kbli' => '91034', 'nama' => 'Taman Wisata Alam ',],
            ['kode_kbli' => '55199', 'nama' => 'Penyediaan Akomodasi Jangka Pendek Lainnya',],
            ['kode_kbli' => '64142', 'nama' => 'Unit Simpan Pinjam Koperasi Primer (USP Koperasi Primer)',],
            ['kode_kbli' => '01121', 'nama' => 'Pertanian Padi Hibrida',],
            ['kode_kbli' => '47512', 'nama' => 'Perdagangan Eceran Perlengkapan Rumah Tangga Dari Tekstil',],
            ['kode_kbli' => '77391', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Mesin dan Peralatan Industri Pengolahan',],
            ['kode_kbli' => '38120', 'nama' => 'Pengumpulan Limbah Berbahaya',],
            ['kode_kbli' => '47749', 'nama' => 'Perdagangan Eceran Barang Bekas Lainnya',],
            ['kode_kbli' => '22112', 'nama' => 'Industri Vulkanisir Ban',],
            ['kode_kbli' => '66411', 'nama' => 'Penyedia Jasa Pembayaran (PJP)',],
            ['kode_kbli' => '32111', 'nama' => 'Industri Permata',],
            ['kode_kbli' => '10613', 'nama' => 'Industri Penggilingan Aneka  Umbi Dan Sayuran (Termasuk Rhizoma)',],
            ['kode_kbli' => '26120', 'nama' => 'Industri Semi Konduktor Dan Komponen Elektronik Lainnya',],
            ['kode_kbli' => '85491', 'nama' => 'Jasa Pendidikan Manajemen Dan Perbankan',],
            ['kode_kbli' => '77400', 'nama' => 'Sewa Guna Usaha Tanpa Hak Opsi Intelektual Properti, Bukan Karya Hak Cipta',],
            ['kode_kbli' => '47736', 'nama' => 'Perdagangan Eceran Perlengkapan Pengendara Kendaraan Bermotor',],
            ['kode_kbli' => '01192', 'nama' => 'Perbenihan Tanaman Pakan Ternak dan Pembibitan Bit (Bukan Bit Gula)',],
            ['kode_kbli' => '16212', 'nama' => 'Industri Kayu Lapis Laminasi, Termasuk Decorative Plywood',],
            ['kode_kbli' => '47794', 'nama' => 'Perdagangan Eceran Alat Transportasi Darat Tidak Bermotor Dan Perlengkapannya',],
            ['kode_kbli' => '88992', 'nama' => 'Aktivitas Sosial Swasta Tanpa Akomodasi Lainnya YTDL',],
            ['kode_kbli' => '01302', 'nama' => 'Pertanian Pengembangbiakan Tanaman ',],
            ['kode_kbli' => '01283', 'nama' => 'Pertanian Cabai',],
            ['kode_kbli' => '86102', 'nama' => 'Aktivitas Puskesmas',],
            ['kode_kbli' => '25931', 'nama' => 'Industri Alat Potong dan Perkakas Tangan Untuk Pertanian',],
            ['kode_kbli' => '10621', 'nama' => 'Industri Pati Ubi Kayu',],
            ['kode_kbli' => '90023', 'nama' => 'Aktivitas Pelaku Kreatif Seni Rupa',],
            ['kode_kbli' => '47744', 'nama' => 'Perdagangan Eceran Barang Listrik Dan Elektronik Bekas',],
            ['kode_kbli' => '85240', 'nama' => 'Pendidikan Menengah Kejuruan/Aliyah Kejuruan Swasta',],
            ['kode_kbli' => '85132', 'nama' => 'Pendidikan Taman Kanak-kanak Swasta/Raudatul Athfal/Bustanul Athfal',],
            ['kode_kbli' => '11052', 'nama' => 'Industri Air Minum Isi Ulang',],
            ['kode_kbli' => '20231', 'nama' => 'Industri Sabun Dan Bahan Pembersih Keperluan Rumah Tangga',],
            ['kode_kbli' => '46633', 'nama' => 'Perdagangan Besar Genteng, Batu Bata, Ubin Dan Sejenisnya Dari Tanah Liat, Kapur, Semen Atau Kaca',],
            ['kode_kbli' => '14131', 'nama' => 'Industri Perlengkapan Pakaian Dari Tekstil',],
            ['kode_kbli' => '01289', 'nama' => 'Pertanian Tanaman Rempah-Rempah, Aromatik/Penyegar, dan Obat Lainnya',],
            ['kode_kbli' => '58200', 'nama' => 'Penerbitan piranti lunak (Software)',],
            ['kode_kbli' => '47861', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Barang Elektronik',],
            ['kode_kbli' => '43902', 'nama' => 'Pemasangan Perancah (Steiger)',],
            ['kode_kbli' => '08102', 'nama' => 'Penggalian Batu Kapur/Gamping',],
            ['kode_kbli' => '77393', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Mesin Dan Peralatan Konstruksi Dan Teknik Sipil',],
            ['kode_kbli' => '81300', 'nama' => 'Aktivitas Perawatan dan Pemeliharaan Taman',],
            ['kode_kbli' => '01286', 'nama' => 'Pertanian Tanaman Obat atau Biofarmaka Non Rimpang',],
            ['kode_kbli' => '01261', 'nama' => 'Perkebunan Buah Kelapa',],
            ['kode_kbli' => '01270', 'nama' => 'Pertanian Tanaman Untuk Bahan Minuman',],
            ['kode_kbli' => '53202', 'nama' => 'Aktivitas Agen Kurir',],
            ['kode_kbli' => '35112', 'nama' => 'Transmisi Tenaga Listrik',],
            ['kode_kbli' => '93224', 'nama' => 'Wisata Pantai',],
            ['kode_kbli' => '35113', 'nama' => 'Distribusi Tenaga Listrik',],
            ['kode_kbli' => '35111', 'nama' => 'Pembangkitan Tenaga Listrik',],
            ['kode_kbli' => '43216', 'nama' => 'Instalasi Sinyal Dan Rambu-rambu Jalan Raya',],
            ['kode_kbli' => '47999', 'nama' => 'Perdagangan eceran bukan di toko, kios, kaki lima dan los pasar lainnya YTDL',],
            ['kode_kbli' => '10222', 'nama' => 'Industri Pengolahan dan Pengawetan Udang Dalam Kaleng',],
            ['kode_kbli' => '62012', 'nama' => 'Aktivitas Pengembangan Aplikasi Perdagangan Melalui Internet (E-Commerce)',],
            ['kode_kbli' => '64951', 'nama' => 'Layanan Pinjam Meminjam Uang Berbasis Teknologi Informasi (Fintech P2P Lending) Konvensional',],
            ['kode_kbli' => '69202', 'nama' => 'Aktivitas Konsultasi Pajak',],
            ['kode_kbli' => '78425', 'nama' => 'Pelatihan Kerja Bisnis dan Manajemen  Swasta ',],
            ['kode_kbli' => '86902', 'nama' => 'Aktivitas Pelayanan Kesehatan Tradisional',],
            ['kode_kbli' => '52291', 'nama' => 'Jasa Pengurusan Transportasi (JPT)',],
            ['kode_kbli' => '59132', 'nama' => 'Aktivitas Distribusi Film,  Video dan Program Televisi Oleh Swasta',],
            ['kode_kbli' => '60102', 'nama' => 'Penyiaran Radio Oleh Swasta',],
            ['kode_kbli' => '63112', 'nama' => 'Aktivitas Hosting dan Ybdi',],
            ['kode_kbli' => '10422', 'nama' => 'Industri Minyak Mentah Kelapa',],
            ['kode_kbli' => '79129', 'nama' => 'Aktivitas Biro Perjalanan Lainnya',],
            ['kode_kbli' => '71209', 'nama' => 'Analisis Dan Uji Teknis Lainnya',],
            ['kode_kbli' => '70202', 'nama' => 'Aktivitas Konsultansi Transportasi',],
            ['kode_kbli' => '74120', 'nama' => 'Aktivitas Desain Interior',],
            ['kode_kbli' => '43299', 'nama' => 'Instalasi Konstruksi Lainnya Ytdl',],
            ['kode_kbli' => '71204', 'nama' => 'Jasa Inspeksi Teknik Instalasi',],
            ['kode_kbli' => '77291', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Alat Pesta',],
            ['kode_kbli' => '85420', 'nama' => 'Pendidikan Kebudayaan',],
            ['kode_kbli' => '10120', 'nama' => 'Kegiatan Rumah Potong Dan Pengepakan Daging Unggas',],
            ['kode_kbli' => '10792', 'nama' => 'Industri Kue Basah',],
            ['kode_kbli' => '18113', 'nama' => 'Industri Pencetakan 3D Printing',],
            ['kode_kbli' => '47773', 'nama' => 'Perdagangan Eceran Bahan Kimia',],
            ['kode_kbli' => '10298', 'nama' => 'Industri pengolahan rumput laut',],
            ['kode_kbli' => '55110', 'nama' => 'Hotel Bintang',],
            ['kode_kbli' => '10330', 'nama' => 'Industri Pengolahan Sari Buah Dan Sayuran',],
            ['kode_kbli' => '72209', 'nama' => 'Penelitian Dan Pengembangan Ilmu Pengetahuan Sosial dan Humaniora Lainnya.',],
            ['kode_kbli' => '03262', 'nama' => 'Jasa Produksi Budidaya Ikan Air Payau',],
            ['kode_kbli' => '46205', 'nama' => 'Perdagangan Besar Binatang Hidup',],
            ['kode_kbli' => '46323', 'nama' => 'Perdagangan Besar Daging Dan Daging Olahan Lainnya',],
            ['kode_kbli' => '10313', 'nama' => 'Industri Pengeringan Buah-buahan Dan Sayuran',],
            ['kode_kbli' => '61999', 'nama' => 'Aktivitas Telekomunikasi Lainnya YTDL',],
            ['kode_kbli' => '10729', 'nama' => 'Industri Pengolahan Gula Lainnya Bukan Sirop',],
            ['kode_kbli' => '10393', 'nama' => 'Industri Pengolahan dan Pengawetan Kedelai dan Kacang-kacangan Lainnya Selain Tahu dan Tempe',],
            ['kode_kbli' => '10311', 'nama' => 'Industri Pengasinan Buah-buahan Dan Sayuran',],
            ['kode_kbli' => '10130', 'nama' => 'Industri Pengolahan dan Pengawetan Produk Daging dan Daging Unggas',],
            ['kode_kbli' => '10796', 'nama' => 'Industri Dodol',],
            ['kode_kbli' => '64131', 'nama' => 'Bank Perkreditan Rakyat ',],
            ['kode_kbli' => '01122', 'nama' => 'Pertanian Padi Inbrida',],
            ['kode_kbli' => '16230', 'nama' => 'Industri Wadah Dari Kayu',],
            ['kode_kbli' => '01630', 'nama' => 'Jasa Pasca Panen',],
            ['kode_kbli' => '21021', 'nama' => 'Industri Bahan Baku Obat Tradisional untuk Manusia',],
            ['kode_kbli' => '20129', 'nama' => 'Industri Pupuk Lainnya',],
            ['kode_kbli' => '16299', 'nama' => 'Industri Barang Dari Kayu, Rotan, Gabus Lainnya YTDL',],
            ['kode_kbli' => '08107', 'nama' => 'Penggalian Tras',],
            ['kode_kbli' => '47713', 'nama' => 'Perdagangan Eceran Pelengkap Pakaian',],
            ['kode_kbli' => '03131', 'nama' => 'Jasa Sarana Produksi Penangkapan Ikan Di Laut',],
            ['kode_kbli' => '23951', 'nama' => 'Industri Barang Dari Semen',],
            ['kode_kbli' => '10633', 'nama' => 'Industri Tepung Beras Dan Tepung Jagung',],
            ['kode_kbli' => '10734', 'nama' => 'Industri Kembang Gula ',],
            ['kode_kbli' => '95220', 'nama' => 'Reparasi Peralatan Rumah Tangga Dan Peralatan Rumah Dan Kebun',],
            ['kode_kbli' => '46322', 'nama' => 'Perdagangan Besar Daging Ayam Dan Daging Ayam Olahan',],
            ['kode_kbli' => '90011', 'nama' => 'Aktivitas Seni Pertunjukan',],
            ['kode_kbli' => '47911', 'nama' => 'Perdagangan Eceran Melalui Media Untuk Komoditi Makanan, Minuman, Tembakau, Kimia, Farmasi, Kosmetik Dan Alat Laboratorium',],
            ['kode_kbli' => '10424', 'nama' => 'Industri Pelet Kelapa',],
            ['kode_kbli' => '45104', 'nama' => 'Perdagangan Eceran Mobil Bekas',],
            ['kode_kbli' => '30120', 'nama' => 'Industri Pembuatan Kapal dan Perahu Untuk Tujuan Wisata atau Rekreasi dan Olahraga',],
            ['kode_kbli' => '33151', 'nama' => 'Reparasi Kapal, Perahu Dan Bangunan Terapung',],
            ['kode_kbli' => '47745', 'nama' => 'Perdagangan Eceran Bahan Konstruksi Dan Sanitasi Bekas',],
            ['kode_kbli' => '47795', 'nama' => 'Perdagangan Eceran Alat Transportasi Air Dan Perlengkapannya',],
            ['kode_kbli' => '01139', 'nama' => 'Pertanian Sayuran, Buah dan Aneka Umbi Lainnya',],
            ['kode_kbli' => '46208', 'nama' => 'Perdagangan Besar Kulit Dan Kulit Jangat',],
            ['kode_kbli' => '46311', 'nama' => 'Perdagangan Besar Beras',],
            ['kode_kbli' => '46315', 'nama' => 'Perdagangan Besar Minyak dan Lemak Nabati',],
            ['kode_kbli' => '46321', 'nama' => 'Perdagangan Besar Daging Sapi Dan Daging Sapi Olahan',],
            ['kode_kbli' => '46325', 'nama' => 'Perdagangan Besar Telur Dan Hasil Olahan Telur',],
            ['kode_kbli' => '46326', 'nama' => 'Perdagangan Besar Susu Dan Produk Susu',],
            ['kode_kbli' => '46327', 'nama' => 'Perdagangan Besar Minyak Dan Lemak Hewani',],
            ['kode_kbli' => '46329', 'nama' => 'Perdagangan Besar Bahan Makanan Dan Minuman Hasil Peternakan Dan Perikanan Lainnya',],
            ['kode_kbli' => '46331', 'nama' => 'Perdagangan Besar Gula, Coklat Dan Kembang Gula',],
            ['kode_kbli' => '46332', 'nama' => 'Perdagangan Besar Produk Roti',],
            ['kode_kbli' => '46419', 'nama' => 'Perdagangan besar tekstil, pakaian dan alas kaki lainnya',],
            ['kode_kbli' => '46441', 'nama' => 'Perdagangan Besar Obat Farmasi Untuk Manusia',],
            ['kode_kbli' => '46492', 'nama' => 'Perdagangan Besar Alat Olahraga',],
            ['kode_kbli' => '46493', 'nama' => 'Perdagangan Besar Alat Musik',],
            ['kode_kbli' => '46495', 'nama' => 'Perdagangan Besar Alat Permainan Dan Mainan Anak-anak',],
            ['kode_kbli' => '46530', 'nama' => 'Perdagangan Besar Mesin, Peralatan Dan Perlengkapan Pertanian',],
            ['kode_kbli' => '46593', 'nama' => 'Perdagangan Besar Alat Transportasi Darat (Bukan Mobil, Sepeda Motor, Dan Sejenisnya), Suku Cadang Dan Perlengkapannya',],
            ['kode_kbli' => '46594', 'nama' => 'Perdagangan Besar Alat Transportasi Udara, Suku Cadang Dan Perlengkapannya',],
            ['kode_kbli' => '46599', 'nama' => 'Perdagangan Besar Mesin, Peralatan Dan Perlengkapan Lainnya',],
            ['kode_kbli' => '01191', 'nama' => 'Pertanian Tanaman Pakan Ternak',],
            ['kode_kbli' => '46635', 'nama' => 'Perdagangan Besar Bahan Konstruksi Dari Porselen',],
            ['kode_kbli' => '46637', 'nama' => 'Perdagangan Besar Cat',],
            ['kode_kbli' => '46639', 'nama' => 'Perdagangan Besar Bahan Konstruksi Lainnya',],
            ['kode_kbli' => '46693', 'nama' => 'Perdagangan Besar Karet Dan Plastik Dalam Bentuk Dasar',],
            ['kode_kbli' => '46694', 'nama' => 'Perdagangan Besar Kertas Dan Karton',],
            ['kode_kbli' => '43212', 'nama' => 'Instalasi Telekomunikasi',],
            ['kode_kbli' => '47792', 'nama' => 'Perdagangan Eceran Mesin Jahit Dan Perlengkapannya',],
            ['kode_kbli' => '61200', 'nama' => 'Aktivitas Telekomunikasi Tanpa Kabel',],
            ['kode_kbli' => '47832', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Pakaian',],
            ['kode_kbli' => '19214', 'nama' => 'Industri Pengolahan Minyak Pelumas Bekas Menjadi Bahan Bakar',],
            ['kode_kbli' => '23129', 'nama' => 'Industri Barang Lainnya Dari Kaca',],
            ['kode_kbli' => '03261', 'nama' => 'Jasa Sarana Produksi Budidaya Ikan Air Payau',],
            ['kode_kbli' => '85493', 'nama' => 'Pendidikan Bahasa Swasta',],
            ['kode_kbli' => '85497', 'nama' => 'Pendidikan Teknik Swasta',],
            ['kode_kbli' => '85498', 'nama' => 'Pendidikan Kerajinan Dan Industri',],
            ['kode_kbli' => '10299', 'nama' => 'Industri Pengolahan Dan Pengawetan Lainnya untuk Biota Air Lainnya',],
            ['kode_kbli' => '30113', 'nama' => 'Industri Peralatan, Perlengkapan Dan Bagian Kapal',],
            ['kode_kbli' => '47823', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Kopi, Gula Pasir, Gula Merah Dan Sejenisnya',],
            ['kode_kbli' => '47879', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Campuran Kertas, Karton, Barang Dari Kertas, Alat Tulis-menulis, Alat Gambar, Hasil Pencetakan, Penerbitan Dan Lainnya',],
            ['kode_kbli' => '93222', 'nama' => 'Wisata Gua',],
            ['kode_kbli' => '47525', 'nama' => 'Perdagangan Eceran Bahan Konstruksi Dari Porselen',],
            ['kode_kbli' => '47852', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Barang Perhiasan',],
            ['kode_kbli' => '10779', 'nama' => 'Industri Produk Masak  Lainnya',],
            ['kode_kbli' => '62024', 'nama' => 'Aktivitas Konsultasi dan Perancangan Internet of Things (IoT)',],
            ['kode_kbli' => '78423', 'nama' => 'Pelatihan Kerja Industri Kreatif  Swasta',],
            ['kode_kbli' => '78427', 'nama' => 'Pelatihan Kerja Pertanian dan Perikanan Swasta',],
            ['kode_kbli' => '78429', 'nama' => 'Pelatihan Kerja Swasta Lainnya',],
            ['kode_kbli' => '78300', 'nama' => 'Penyediaan Sumber Daya Manusia dan Manajemen Fungsi Sumber Daya Manusia',],
            ['kode_kbli' => '22299', 'nama' => 'Industri Barang Plastik Lainnya Ytdl',],
            ['kode_kbli' => '85139', 'nama' => 'Pendidikan anak usia dini sejenis lainnya',],
            ['kode_kbli' => '85134', 'nama' => 'Pendidikan Taman Penitipan Anak',],
            ['kode_kbli' => '85141', 'nama' => 'Satuan Pendidikan Kerjasama Kelompok Bermain',],
            ['kode_kbli' => '93292', 'nama' => 'Karaoke',],
            ['kode_kbli' => '47221', 'nama' => 'Perdagangan Eceran Minuman Beralkohol',],
            ['kode_kbli' => '01623', 'nama' => 'Jasa Penetasan Telur',],
            ['kode_kbli' => '74202', 'nama' => 'Aktivitas Angkutan Udara Khusus Pemotretan, Survei Dan Pemetaan',],
            ['kode_kbli' => '47530', 'nama' => 'Perdagangan Eceran Khusus Karpet, Permadani dan Penutup Dinding dan Lantai di Toko',],
            ['kode_kbli' => '47522', 'nama' => 'Perdagangan Eceran Kaca',],
            ['kode_kbli' => '47245', 'nama' => 'Perdagangan Eceran Daging dan Ikan Olahan',],
            ['kode_kbli' => '01412', 'nama' => 'Pembibitan Dan Budidaya Sapi Perah',],
            ['kode_kbli' => '01413', 'nama' => 'Pembibitan Dan Budidaya Kerbau Potong',],
            ['kode_kbli' => '01414', 'nama' => 'Pembibitan Dan Budidaya Kerbau Perah',],
            ['kode_kbli' => '01444', 'nama' => 'Pembibitan Dan Budidaya Domba Perah',],
            ['kode_kbli' => '47727', 'nama' => 'Perdagangan Eceran Obat Tradisional Untuk Hewan',],
            ['kode_kbli' => '91029', 'nama' => 'Wisata Budaya Lainnya',],
            ['kode_kbli' => '41020', 'nama' => 'Jasa Pekerjaan Konstruksi Prapabrikasi Bangunan Gedung',],
            ['kode_kbli' => '42104', 'nama' => 'Konstruksi Terowongan',],
            ['kode_kbli' => '42912', 'nama' => 'Konstruksi Bangunan Pelabuhan Bukan Perikanan',],
            ['kode_kbli' => '42914', 'nama' => 'Pengerukan',],
            ['kode_kbli' => '42915', 'nama' => 'Konstruksi Bangunan Sipil Minyak dan Gas Bumi ',],
            ['kode_kbli' => '42916', 'nama' => 'Konstruksi Bangunan Sipil Pertambangan ',],
            ['kode_kbli' => '42917', 'nama' => 'Konstruksi Bangunan Sipil Panas Bumi ',],
            ['kode_kbli' => '42922', 'nama' => 'Jasa Pekerjaan Konstruksi Pelindung Pantai',],
            ['kode_kbli' => '42923', 'nama' => 'Konstruksi Bangunan Sipil Fasilitas Pengolahan Produk Kimia, Petrokimia, Farmasi, dan Industri Lainnya',],
            ['kode_kbli' => '42930', 'nama' => 'Jasa Pekerjaan Konstruksi Prapabrikasi Bangunan Sipil',],
            ['kode_kbli' => '43110', 'nama' => 'Pembongkaran',],
            ['kode_kbli' => '43214', 'nama' => 'Jasa Instalasi Konstruksi Navigasi Laut, Sungai, dan Udara',],
            ['kode_kbli' => '43215', 'nama' => 'Instalasi Sinyal Dan Telekomunikasi Kereta Api',],
            ['kode_kbli' => '43222', 'nama' => 'Instalasi Pemanas Dan Geotermal',],
            ['kode_kbli' => '43223', 'nama' => 'Instalasi Minyak Dan Gas',],
            ['kode_kbli' => '43292', 'nama' => 'Instalasi Meteorologi, Klimatologi  Dan Geofisika',],
            ['kode_kbli' => '43302', 'nama' => 'Pengerjaan Lantai, Dinding, Peralatan Saniter Dan Plafon',],
            ['kode_kbli' => '43901', 'nama' => 'Pemasangan Pondasi Dan Tiang Pancang',],
            ['kode_kbli' => '43903', 'nama' => 'Pemasangan Rangka dan Atap/Roof Covering',],
            ['kode_kbli' => '43905', 'nama' => 'Penyewaan Alat Konstruksi Dengan Operator',],
            ['kode_kbli' => '45101', 'nama' => 'Perdagangan Besar Mobil Baru',],
            ['kode_kbli' => '45102', 'nama' => 'Perdagangan Besar Mobil Bekas',],
            ['kode_kbli' => '45405', 'nama' => 'Perdagangan Besar Suku Cadang Sepeda Motor Dan Aksesorinya',],
            ['kode_kbli' => '46442', 'nama' => 'Perdagangan Besar Obat Tradisional Untuk Manusia',],
            ['kode_kbli' => '46443', 'nama' => 'Perdagangan Besar Kosmetik Untuk Manusia',],
            ['kode_kbli' => '78422', 'nama' => 'Pelatihan Kerja Teknologi Informasi dan Komunikasi Swasta',],
            ['kode_kbli' => '93293', 'nama' => 'Usaha Arena Permainan',],
            ['kode_kbli' => '85133', 'nama' => 'Pendidikan Kelompok Bermain',],
            ['kode_kbli' => '77323', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Tanpa Hak Opsi Alat Kebutuhan MICE ',],
            ['kode_kbli' => '56301', 'nama' => 'Bar',],
            ['kode_kbli' => '55194', 'nama' => 'Apartemen Hotel',],
            ['kode_kbli' => '42103', 'nama' => 'Konstruksi Jalan Rel',],
            ['kode_kbli' => '47892', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Bahan Bakar Minyak, Gas, Minyak Pelumas Dan Bahan Bakar Lainnya',],
            ['kode_kbli' => '25993', 'nama' => 'Industri Keperluan Rumah Tangga Dari Logam Bukan Peralatan Dapur dan Peralatan Meja',],
            ['kode_kbli' => '01194', 'nama' => 'Pertanian Pembibitan Tanaman Bunga',],
            ['kode_kbli' => '23953', 'nama' => 'Industri Barang Dari Semen Dan Kapur Untuk Konstruksi',],
            ['kode_kbli' => '10763', 'nama' => 'Industri Pengolahan Teh',],
            ['kode_kbli' => '03219', 'nama' => 'Budidaya Biota Air Laut Lainnya',],
            ['kode_kbli' => '61923', 'nama' => 'Jasa Televisi Protokol Internet (IPTV)',],
            ['kode_kbli' => '61929', 'nama' => 'Jasa Multimedia Lainnya',],
            ['kode_kbli' => '93299', 'nama' => 'Aktivitas Hiburan dan Rekreasi Lainnya Ytdl',],
            ['kode_kbli' => '10423', 'nama' => 'Industri Minyak Goreng Kelapa',],
            ['kode_kbli' => '25933', 'nama' => 'Industri Alat Potong Dan Perkakas Tangan Yang Digunakan Dalam Rumah Tangga',],
            ['kode_kbli' => '62021', 'nama' => 'Aktivitas Konsultasi Keamanan Informasi',],
            ['kode_kbli' => '63111', 'nama' => 'Aktivitas Pengolahan Data',],
            ['kode_kbli' => '49219', 'nama' => 'Angkutan Bus Dalam Trayek Lainnya',],
            ['kode_kbli' => '47813', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Komoditi Sayur-sayuran',],
            ['kode_kbli' => '85122', 'nama' => 'Pendidikan Menengah Pertama/Tsanawiyah Swasta',],
            ['kode_kbli' => '95291', 'nama' => 'Aktivitas Vermak Pakaian',],
            ['kode_kbli' => '47881', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Barang Kerajinan',],
            ['kode_kbli' => '37012', 'nama' => 'Pengumpulan Air Limbah Berbahaya',],
            ['kode_kbli' => '03114', 'nama' => 'Penangkapan/Pengambilan Tumbuhan Air Di Laut',],
            ['kode_kbli' => '10392', 'nama' => 'Industri Tahu Kedelai',],
            ['kode_kbli' => '26490', 'nama' => 'Industri Peralatan Audio dan Video Elektronik Lainnya',],
            ['kode_kbli' => '10399', 'nama' => 'Industri Pengolahan dan Pengawetan Lainnya Buah-buahan Dan Sayuran Bukan Kacang-kacangan',],
            ['kode_kbli' => '47244', 'nama' => 'Perdagangan Eceran Tahu, Tempe, Tauco dan Oncom',],
            ['kode_kbli' => '75000', 'nama' => 'Aktivitas Kesehatan Hewan',],
            ['kode_kbli' => '20294', 'nama' => 'Industri Minyak Atsiri',],
            ['kode_kbli' => '10740', 'nama' => 'Industri Makaroni, Mie Dan Produk Sejenisnya',],
            ['kode_kbli' => '10421', 'nama' => 'Industri Kopra',],
            ['kode_kbli' => '03252', 'nama' => 'Pembenihan Ikan Air Payau',],
            ['kode_kbli' => '47829', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Komoditi Makanan Dan Minuman Ytdl',],
            ['kode_kbli' => '36002', 'nama' => 'Penampungan dan Penyaluran Air Baku',],
            ['kode_kbli' => '82301', 'nama' => 'Jasa Penyelenggara Pertemuan, Perjalanan Insentif, Konferensi dan Pameran (MICE)',],
            ['kode_kbli' => '01284', 'nama' => 'Perkebunan Tanaman Aromatik/Penyegar',],
            ['kode_kbli' => '77295', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Alat  Musik',],
            ['kode_kbli' => '90022', 'nama' => 'Pelaku Kreatif Seni Musik ',],
            ['kode_kbli' => '28262', 'nama' => 'Industri Mesin Jahit Serta Mesin Cuci Dan Mesin Pengering Untuk Keperluan Niaga',],
            ['kode_kbli' => '08999', 'nama' => 'Pertambangan Dan Penggalian Lainnya Ytdl',],
            ['kode_kbli' => '09900', 'nama' => 'Aktivitas Penunjang pertambangan dan penggalian lainnya',],
            ['kode_kbli' => '42929', 'nama' => 'Konstruksi Khusus Bangunan Sipil Lainnya Ytdl',],
            ['kode_kbli' => '01281', 'nama' => 'Perkebunan Lada',],
            ['kode_kbli' => '25932', 'nama' => 'Industri Alat Potong dan Perkakas Tangan Pertukangan',],
            ['kode_kbli' => '93113', 'nama' => 'Fasilitas Gelanggang/Arena',],
            ['kode_kbli' => '16215', 'nama' => 'Industri Kayu Laminasi',],
            ['kode_kbli' => '16222', 'nama' => 'Industri Bangunan Prafabrikasi Dari Kayu',],
            ['kode_kbli' => '74112', 'nama' => 'Aktivitas  Desain Peralatan Rumah Tangga dan Furnitur',],
            ['kode_kbli' => '95240', 'nama' => 'Reparasi Furnitur Dan Perlengkapan Rumah',],
            ['kode_kbli' => '64911', 'nama' => 'Perusahaan Pembiayaan Konvensional',],
            ['kode_kbli' => '10411', 'nama' => 'Industri Minyak Mentah dan Lemak Nabati',],
            ['kode_kbli' => '15129', 'nama' => 'Industri Barang Dari Kulit Dan Kulit Komposisi Untuk Keperluan Lainnya',],
            ['kode_kbli' => '10773', 'nama' => 'Industri Produk Masak Dari Kelapa',],
            ['kode_kbli' => '23959', 'nama' => 'Industri Barang Dari Semen, Kapur, Gips dan Asbes Lainnya',],
            ['kode_kbli' => '47741', 'nama' => 'Perdagangan Eceran Barang Bekas Perlengkapan Rumah Tangga',],
            ['kode_kbli' => '13929', 'nama' => 'Industri Barang Jadi Tekstil Lainnya',],
            ['kode_kbli' => '47742', 'nama' => 'Perdagangan Eceran Pakaian, Alas Kaki Dan Pelengkap Pakaian Bekas',],
            ['kode_kbli' => '77311', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Alat Transportasi Darat Bukan Kendaraan Bermotor Roda Empat Atau Lebih',],
            ['kode_kbli' => '56306', 'nama' => 'Penyediaan Minuman Keliling/Tempat Tidak Tetap',],
            ['kode_kbli' => '49414', 'nama' => 'Angkutan Perdesaan Bukan Bus, Dalam Trayek',],
            ['kode_kbli' => '13924', 'nama' => 'Industri Barang Jadi Rajutan dan Sulaman',],
            ['kode_kbli' => '01113', 'nama' => 'Pertanian Kedelai',],
            ['kode_kbli' => '02140', 'nama' => 'Pengusahaan Perbenihan Tanaman Kehutanan ',],
            ['kode_kbli' => '01611', 'nama' => 'Jasa Pengolahan Lahan',],
            ['kode_kbli' => '73202', 'nama' => 'Jajak Pendapat Masyarakat',],
            ['kode_kbli' => '47734', 'nama' => 'Perdagangan Eceran Jam',],
            ['kode_kbli' => '47822', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Roti, Kue Kering, Kue Basah Dan Sejenisnya',],
            ['kode_kbli' => '47824', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Tahu, Tempe, Tauco Dan Oncom',],
            ['kode_kbli' => '47827', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Rokok Dan Tembakau',],
            ['kode_kbli' => '10110', 'nama' => 'Kegiatan Rumah Potong Dan Pengepakan Daging Bukan Unggas',],
            ['kode_kbli' => '47864', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Barang Pecah Belah Dan Perlengkapan Dapur Dari Batu Atau Tanah Liat',],
            ['kode_kbli' => '77329', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Tanpa Hak Opsi Mesin dan Peralatan Industri Kreatif Lainnya',],
            ['kode_kbli' => '77321', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Tanpa Hak Opsi Alat Perekaman Gambar & Editing',],
            ['kode_kbli' => '10723', 'nama' => 'Industri Sirop',],
            ['kode_kbli' => '01262', 'nama' => 'Perkebunan Buah Kelapa Sawit',],
            ['kode_kbli' => '77299', 'nama' => 'Aktivitas penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Barang Keperluan Rumah Tangga Dan Pribadi Lainnya YTDL',],
            ['kode_kbli' => '69201', 'nama' => 'Aktivitas Akuntansi, Pembukuan dan Pemeriksa',],
            ['kode_kbli' => '69103', 'nama' => 'Aktivitas konsultan kekayaan intelektual',],
            ['kode_kbli' => '47992', 'nama' => 'Perdagangan Eceran Keliling Komoditi Makanan, Minuman Atau Tembakau Hasil Industri Pengolahan',],
            ['kode_kbli' => '10632', 'nama' => 'Industri Penggilingan Dan Pembersihan Jagung',],
            ['kode_kbli' => '86901', 'nama' => 'Aktivitas pelayanan kesehatan yang dilakukan oleh tenaga kesehatan selain dokter dan dokter gigi',],
            ['kode_kbli' => '32402', 'nama' => 'Industri Mainan Anak-anak',],
            ['kode_kbli' => '16294', 'nama' => 'Industri Alat Dapur Dari Kayu, Rotan Dan Bambu',],
            ['kode_kbli' => '27320', 'nama' => 'Industri Kabel Listrik Dan Elektronik Lainnya',],
            ['kode_kbli' => '32113', 'nama' => 'Industri Barang Perhiasan Dari Logam Mulia Bukan Untuk Keperluan Pribadi',],
            ['kode_kbli' => '23929', 'nama' => 'Industri Bahan Bangunan Dari Tanah Liat/Keramik Bukan Batu Bata Dan Genteng',],
            ['kode_kbli' => '78435', 'nama' => 'Pelatihan Kerja Bisnis dan Manajemen  Perusahaan',],
            ['kode_kbli' => '47774', 'nama' => 'Perdagangan Eceran Aromatik/Penyegar (Minyak Atsiri)',],
            ['kode_kbli' => '10733', 'nama' => 'Industri Manisan Buah-buahan Dan Sayuran Kering',],
            ['kode_kbli' => '10532', 'nama' => 'Industri Pengolahan Es Sejenisnya Yang Dapat Dimakan (Bukan Es Batu dan Es Balok)',],
            ['kode_kbli' => '47998', 'nama' => 'Perdagangan Eceran Keliling Barang Kerajinan, Mainan Anak-anak Dan Lukisan',],
            ['kode_kbli' => '31002', 'nama' => 'Industri Furnitur Dari Rotan Dan Atau Bambu',],
            ['kode_kbli' => '10214', 'nama' => 'Industri Pemindangan Ikan',],
            ['kode_kbli' => '85121', 'nama' => 'Pendidikan Dasar/Ibtidaiyah  Swasta',],
            ['kode_kbli' => '85220', 'nama' => 'Pendidikan Menengah/Aliyah Swasta',],
            ['kode_kbli' => '74141', 'nama' => 'Aktivitas Desain Khusus Film, Video, Program TV, Animasi dan Komik',],
            ['kode_kbli' => '38212', 'nama' => 'Produksi Kompos Sampah Organik',],
            ['kode_kbli' => '47764', 'nama' => 'Perdagangan Eceran Perlengkapan Dan Media Tanaman Hias',],
            ['kode_kbli' => '52240', 'nama' => 'Penanganan Kargo (Bongkar Muat Barang)',],
            ['kode_kbli' => '20115', 'nama' => 'Industri Kimia Dasar Organik Yang Bersumber Dari Hasil Pertanian',],
            ['kode_kbli' => '10739', 'nama' => 'Industri Kembang Gula Lainnya',],
            ['kode_kbli' => '08108', 'nama' => 'Penggalian Batu Apung',],
            ['kode_kbli' => '08104', 'nama' => 'Penggalian Pasir',],
            ['kode_kbli' => '20232', 'nama' => 'Industri Kosmetik Untuk Manusia, Termasuk Pasta Gigi',],
            ['kode_kbli' => '16105', 'nama' => 'Industri Partikel Kayu dan Sejenisnya',],
            ['kode_kbli' => '10314', 'nama' => 'Industri Pembekuan Buah-buahan Dan Sayuran',],
            ['kode_kbli' => '01495', 'nama' => 'Pembibitan Dan Budidaya Kelinci',],
            ['kode_kbli' => '32503', 'nama' => 'Industri Kaca Mata',],
            ['kode_kbli' => '28264', 'nama' => 'Industri Jarum Mesin Jahit, Rajut, Bordir Dan Sejenisnya',],
            ['kode_kbli' => '10774', 'nama' => 'Industri Pengolahan Garam',],
            ['kode_kbli' => '33141', 'nama' => 'Reparasi Motor Listrik, Generator Dan Transformator',],
            ['kode_kbli' => '10212', 'nama' => 'Industri Pengasapan/Pemanggangan Ikan',],
            ['kode_kbli' => '10415', 'nama' => 'Industri Minyak Goreng Bukan Minyak Kelapa Dan Minyak Kelapa Sawit',],
            ['kode_kbli' => '28240', 'nama' => 'Industri Mesin Penambangan, Penggalian Dan Konstruksi',],
            ['kode_kbli' => '10732', 'nama' => 'Industri Makanan Dari Cokelat Dan Kembang Gula dari Coklat',],
            ['kode_kbli' => '47821', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Beras',],
            ['kode_kbli' => '77294', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Bunga Dan Tanaman Hias',],
            ['kode_kbli' => '93191', 'nama' => 'Promotor Kegiatan Olahraga',],
            ['kode_kbli' => '64151', 'nama' => 'Lembaga Keuangan Mikro Konvensional',],
            ['kode_kbli' => '10293', 'nama' => 'Industri Pembekuan Biota Air Lainnya',],
            ['kode_kbli' => '01133', 'nama' => 'Pertanian Hortikultura Sayuran Buah',],
            ['kode_kbli' => '18201', 'nama' => 'Reproduksi Media Rekaman Suara dan Piranti Lunak',],
            ['kode_kbli' => '16292', 'nama' => 'Industri barang Anyaman Dari Tanaman Bukan Rotan Dan Bambu',],
            ['kode_kbli' => '22292', 'nama' => 'Industri Perlengkapan Dan Peralatan Rumah Tangga (tidak Termasuk Furnitur)',],
            ['kode_kbli' => '47814', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Komoditi Hasil Peternakan',],
            ['kode_kbli' => '01132', 'nama' => 'Pertanian Hortikultura Buah',],
            ['kode_kbli' => '10590', 'nama' => 'Industri Pengolahan Produk dari Susu Lainnya',],
            ['kode_kbli' => '63990', 'nama' => 'Aktivitas Jasa Informasi Lainnya YTDL',],
            ['kode_kbli' => '32901', 'nama' => 'Industri Alat Tulis Dan Gambar Termasuk Perlengkapannya',],
            ['kode_kbli' => '17099', 'nama' => 'Industri Barang Dari Kertas Dan Papan Kertas Lainnya YTDL',],
            ['kode_kbli' => '79921', 'nama' => 'Jasa Pramuwisata',],
            ['kode_kbli' => '77319', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Alat Transportasi Lainnya',],
            ['kode_kbli' => '01301', 'nama' => 'Pertanian Tanaman Hias ',],
            ['kode_kbli' => '49415', 'nama' => 'Angkutan Darat Khusus Bukan Bus',],
            ['kode_kbli' => '59122', 'nama' => 'Aktivitas Pascaproduksi Film,  Video dan Program Televisi Oleh Swasta',],
            ['kode_kbli' => '26220', 'nama' => 'Industri Perlengkapan Komputer',],
            ['kode_kbli' => '22220', 'nama' => 'Industri Barang Dari Plastik Untuk Pengemasan',],
            ['kode_kbli' => '13911', 'nama' => 'Industri Kain Rajutan',],
            ['kode_kbli' => '28221', 'nama' => 'Industri Mesin dan Perkakas Mesin Untuk Pengerjaan Logam',],
            ['kode_kbli' => '80100', 'nama' => 'Aktivitas Keamanan Swasta',],
            ['kode_kbli' => '13991', 'nama' => 'Industri Kain Pita (Narrow Fabric)',],
            ['kode_kbli' => '12012', 'nama' => 'Industri Rokok Putih',],
            ['kode_kbli' => '20121', 'nama' => 'Industri Pupuk Alam/Non Sintetis Hara Makro Primer',],
            ['kode_kbli' => '47732', 'nama' => 'Perdagangan Eceran Alat Optik Dan Perlengkapannya',],
            ['kode_kbli' => '01230', 'nama' => 'Pertanian Buah Jeruk',],
            ['kode_kbli' => '85500', 'nama' => 'Kegiatan Penunjang Pendidikan',],
            ['kode_kbli' => '64190', 'nama' => 'Perantara moneter lainnya',],
            ['kode_kbli' => '90021', 'nama' => 'Pelaku Kreatif Seni Pertunjukan ',],
            ['kode_kbli' => '85440', 'nama' => 'Satuan Pendidikan Kerjasama Pendidikan NonFormal ',],
            ['kode_kbli' => '85410', 'nama' => 'Jasa Pendidikan Olahraga Dan Rekreasi',],
            ['kode_kbli' => '85499', 'nama' => 'Pendidikan Lainnya Swasta',],
            ['kode_kbli' => '32401', 'nama' => 'Industri Alat Permainan',],
            ['kode_kbli' => '13133', 'nama' => 'Industri Pencetakan Kain',],
            ['kode_kbli' => '62011', 'nama' => 'Aktivitas Pengembangan Video game',],
            ['kode_kbli' => '62013', 'nama' => 'Aktivitas Pemrograman dan Produksi Konten Media Imersif',],
            ['kode_kbli' => '03243', 'nama' => 'Jasa Pasca Panen Budidaya Ikan Air Tawar',],
            ['kode_kbli' => '20211', 'nama' => 'Industri Bahan Baku Pemberantas Hama (Bahan Aktif)',],
            ['kode_kbli' => '10211', 'nama' => 'Industri Penggaraman/Pengeringan Ikan',],
            ['kode_kbli' => '28112', 'nama' => 'Industri Motor Pembakaran Dalam',],
            ['kode_kbli' => '47844', 'nama' => 'Perdagangan Eceran Kaki Lima Dan Los Pasar Kosmetik',],
            ['kode_kbli' => '86904', 'nama' => 'Aktivitas Angkutan Khusus Pengangkutan Orang Sakit (Medical Evacuation)',],
            ['kode_kbli' => '81290', 'nama' => 'Aktivitas Kebersihan Bangunan Dan Industri Lainnya',],
            ['kode_kbli' => '13942', 'nama' => 'Industri Barang Dari Tali',],
            ['kode_kbli' => '23943', 'nama' => 'Industri Gips',],
            ['kode_kbli' => '85142', 'nama' => 'Satuan Pendidikan Kerjasama Taman Kanak-Kanak',],
            ['kode_kbli' => '03213', 'nama' => 'Budidaya Ikan Hias Air Laut',],
            ['kode_kbli' => '45103', 'nama' => 'Perdagangan Eceran Mobil Baru',],
            ['kode_kbli' => '46333', 'nama' => 'Perdagangan Besar Minuman Beralkohol',],
            ['kode_kbli' => '31003', 'nama' => 'Industri Furnitur Dari Plastik',],
            ['kode_kbli' => '77210', 'nama' => 'Aktivitas Penyewaan dan Sewa Guna Usaha Tanpa Hak Opsi Alat rekreasi dan Olahraga',],
            ['kode_kbli' => '10531', 'nama' => 'Industri Pengolahan Es Krim',],             
        ];
        Db::table('kblis')->insert($data);
    }
}
